version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_backend
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development  # Altere para "production" em produção
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: